version: '3'

services:
  web-app: &web-app-config
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      DB_CONN_URI: postgresql+psycopg2://user:password@pg:5432/blog.db
      FLASK_ENV: development
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - pg

  pg:
    image: postgres # use latest official postgres version
    env_file:
      - postgres.env # configure postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    healthcheck:
      test: ["CMD-SHELL", "pg_isready blog.db -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
